apiVersion: v1
kind: Template
metadata:
  name: jenkinsTemplate 
  annotations:
    description: "Description" 
    iconClass: "icon-redis" 
objects:
# jenkins
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: cicd-jenkins
  spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
      - ReadWriteMany
    nfs:
      server: 10.1.2.2
      path: /opt/storage/cicd-jenkins
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: cicd-jenkins
  spec:
    accessModes:
      - ReadWriteOnce
      - ReadWriteMany
    resources:
      requests:
        storage: 4Gi
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: jenkins
    name: jenkins
  spec:
    ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: jnlp
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      app: jenkins
      deploymentconfig: jenkins
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: jenkins
    name: jenkins
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: jenkins
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: jenkins
    name: jenkins
  spec:
    replicas: 1
    selector:
      app: jenkins
      deploymentconfig: jenkins
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: jenkins
          deploymentconfig: jenkins
      spec:
        volumes:
          -
            name: cicd-jenkins
            persistentVolumeClaim:
              claimName: cicd-jenkins
        containers:
        - image: jenkins:latest
          name: jenkins
          ports:
          - containerPort: 8080
            protocol: TCP
          volumeMounts:
            -
              name: cicd-jenkins
              mountPath: /var/jenkins_home
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
