apiVersion: v1
kind: Template
metadata:
  name: create nexus 
  annotations:
    description: "Description" 
    iconClass: "icon-redis" 
objects:   
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: cicd-nexus
  spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
      - ReadWriteMany
    nfs:
      server: 10.1.2.2
      path: /opt/storage/cicd-nexus
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: cicd-nexus
  spec:
    accessModes:
      - ReadWriteOnce
      - ReadWriteMany
    resources:
      requests:
        storage: 4Gi
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Sonatype Nexus repository manager's http port
    labels:
      app: nexus
    name: nexus
  spec:
    ports:
    - name: web
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: nexus
      deploymentconfig: nexus
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: nexus
    name: nexus
  spec:
    port:
      targetPort: web
    to:
      kind: Service
      name: nexus
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: nexus
    name: nexus
  spec:
    replicas: 1
    selector:
      app: nexus
      deploymentconfig: nexus
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: nexus
          deploymentconfig: nexus
      spec:
        volumes:
          -
            name: cicd-nexus
            persistentVolumeClaim:
              claimName: cicd-nexus
        containers:
        - image: sonatype/nexus:latest
          name: nexus
          ports:
          - containerPort: 8081
            protocol: TCP
          volumeMounts:
            -
              name: cicd-nexus
              mountPath: /sonatype-work